# fly.toml app configuration file generated for postlitebox on 2025-02-14T13:39:15Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'postlitebox'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 4200
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
